# Generated by Django 4.1.6 on 2023-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.CharField(max_length=100)),
                ("tweet_created_at", models.DateTimeField()),
                ("tweet_date", models.DateTimeField()),
                ("tweet_time", models.TimeField()),
                ("tweet_user_name", models.CharField(max_length=100)),
                ("tweet_name", models.CharField(max_length=100)),
                ("tweet_text", models.CharField(max_length=1000)),
                ("tweet_lang", models.CharField(max_length=100)),
                ("tweet_mentions", models.CharField(max_length=100)),
                ("tweet_photos", models.CharField(max_length=100)),
                ("tweet_replies_count", models.IntegerField()),
                ("tweet_retweets_count", models.IntegerField()),
                ("tweet_likes_count", models.IntegerField()),
                ("tweet_hashtags", models.CharField(max_length=100)),
                ("tweet_urls", models.CharField(max_length=100)),
                ("tweet_retweet", models.CharField(max_length=100)),
                ("tweet_video", models.CharField(max_length=100)),
                ("tweet_reply_to", models.CharField(max_length=100)),
            ],
        ),
    ]
