# Generated by Django 4.1.6 on 2023-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DSPITweetsAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="tweet_views_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
