# Generated by Django 4.1.6 on 2023-02-04 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("DSPITweetsAPP", "0002_tweet_tweet_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="tweet_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
