# Generated by Django 4.1.6 on 2023-02-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DSPITweetsAPP", "0004_alter_tweet_tweet_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet", name="tweet_date", field=models.DateField(),
        ),
    ]
