# Generated by Django 4.1.6 on 2023-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DSPITweetsAPP", "0007_alter_tweet_tweet_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_id", models.DecimalField(decimal_places=0, max_digits=25)),
                ("tweet_sentiment", models.FloatField()),
            ],
        ),
    ]
