# Generated by Django 4.1.6 on 2023-02-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DSPITweetsAPP", "0008_sentimentanalysis"),
    ]

    operations = [
        migrations.DeleteModel(name="SentimentAnalysis",),
        migrations.AddField(
            model_name="tweet",
            name="tweet_sentiment",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
