# Generated by Django 4.1.6 on 2023-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DSPITweetsAPP", "0009_delete_sentimentanalysis_tweet_tweet_sentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RussianTweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ru_tweet_id", models.DecimalField(decimal_places=0, max_digits=25)),
                ("ru_tweet_created_at", models.CharField(max_length=100)),
                ("ru_tweet_date", models.DateField()),
                ("ru_tweet_time", models.TimeField()),
                ("ru_tweet_user_name", models.CharField(max_length=100)),
                ("ru_tweet_name", models.CharField(max_length=100)),
                ("ru_tweet_text", models.CharField(max_length=1000)),
                ("ru_tweet_lang", models.CharField(max_length=100)),
                ("ru_tweet_mentions", models.CharField(max_length=100)),
                ("ru_tweet_photos", models.CharField(max_length=100)),
                ("ru_tweet_replies_count", models.IntegerField()),
                ("ru_tweet_retweets_count", models.IntegerField()),
                ("ru_tweet_likes_count", models.IntegerField()),
                ("ru_tweet_hashtags", models.CharField(max_length=100)),
                ("ru_tweet_urls", models.CharField(max_length=100)),
                ("ru_tweet_retweet", models.CharField(max_length=100)),
                ("ru_tweet_video", models.CharField(max_length=100)),
                ("ru_tweet_reply_to", models.CharField(max_length=100)),
                ("ru_tweet_views_count", models.IntegerField()),
                ("ru_tweet_sentiment", models.FloatField()),
            ],
        ),
        migrations.RenameModel(old_name="Tweet", new_name="WestTweet",),
    ]
